"""initiate migrations

Revision ID: e1d6ed8e1438
Revises: 
Create Date: 2026-08-26 13:09:00.276540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d6ed8e1438'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADA', 'OCUPADA', 'EM_LIMPEZA', 'INDISPONIVEL', 'CONFIRMADA', 'CANCELADA', name='statusmesa'), nullable=False),
    sa.Column('tipo', sa.Enum('PADRAO', 'JANTAR', 'VIP', 'EXTERNA', 'BAR', name='tipomesa'), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesas_numero'), 'mesas', ['numero'], unique=True)
    op.create_index(op.f('ix_mesas_public_id'), 'mesas', ['public_id'], unique=True)
    op.create_table('produtos',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('ENTRADA', 'PRINCIPAL', 'GUARNICAO', 'SOBREMESA', 'BEBIDA', 'REFRIGERANTE', 'SUCOS', 'CERVEJA', 'VINHO', 'CAFE', 'PETISCO', 'PORCOES', 'DOCES', 'SALGADOS', 'VEGETARIANO', 'VEGANO', name='categoriaproduto'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_public_id'), 'produtos', ['public_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('user_type', sa.Enum('CLIENT', 'ADMIN', name='usertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index('ix_reset_token_expires', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('ix_reset_token_user_lookup', 'password_reset_tokens', ['user_id', 'token'], unique=False)
    op.create_table('reservas_mesa',
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(length=100), nullable=False),
    sa.Column('cliente_telefone', sa.String(length=20), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('numero_pessoas', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADA', 'OCUPADA', 'EM_LIMPEZA', 'INDISPONIVEL', 'CONFIRMADA', 'CANCELADA', name='statusmesa'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.String(length=300), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_mesa_public_id'), 'reservas_mesa', ['public_id'], unique=True)
    op.create_table('pedidos',
    sa.Column('mesa_numero', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(length=100), nullable=False),
    sa.Column('cliente_telefone', sa.String(length=20), nullable=False),
    sa.Column('cliente_tipo', sa.Enum('REGISTRADO', 'CONVIDADO', name='tipocliente'), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_PAGAMENTO', 'AGUARDANDO_CONFIRMACAO_MANUAL', 'PAGO', 'PREPARANDO', 'PRONTO', 'ENTREGUE', 'CANCELADO', name='statuspedido'), nullable=False),
    sa.Column('origem', sa.Enum('PRESENCIAL', 'DELIVERY', 'RESERVA', name='origempedido'), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tempo_preparo_estimado', sa.Integer(), nullable=True),
    sa.Column('pagamento_manual', sa.Boolean(), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('EMIS', 'DINHEIRO', 'TRANSFERENCIA', 'POS', 'BOLETO', name='metodopagamento'), nullable=True),
    sa.Column('pagamento_autorizado_por', sa.String(length=100), nullable=True),
    sa.Column('transacao_id', sa.String(length=100), nullable=True),
    sa.Column('pagamento_dados', sa.JSON(), nullable=True),
    sa.Column('pagamento_confirmado_em', sa.DateTime(), nullable=True),
    sa.Column('codigo_autorizacao', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('reserva_mesa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reserva_mesa_id'], ['reservas_mesa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_public_id'), 'pedidos', ['public_id'], unique=True)
    op.create_index(op.f('ix_pedidos_reserva_mesa_id'), 'pedidos', ['reserva_mesa_id'], unique=False)
    op.create_table('itens_pedido',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_public_id'), 'itens_pedido', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_pedido_public_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_pedidos_reserva_mesa_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_public_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_reservas_mesa_public_id'), table_name='reservas_mesa')
    op.drop_table('reservas_mesa')
    op.drop_index('ix_reset_token_user_lookup', table_name='password_reset_tokens')
    op.drop_index('ix_reset_token_expires', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_produtos_public_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_mesas_public_id'), table_name='mesas')
    op.drop_index(op.f('ix_mesas_numero'), table_name='mesas')
    op.drop_table('mesas')
    # ### end Alembic commands ###
